blueprint:
  name: Chauffage Mode
  description: Gestion des différents modes de chauffage
  domain: automation

  input:
    temperature_confort:
      name: Température Confort
      selector:
        number:
          min: 14
          max: 22
          step: 0.5
          mode: slider
          
    temperature_eco:
      name: Température Eco
      selector:
        number:
          min: 14
          max: 22
          step: 0.5
          mode: slider

description: ''
trigger:
  - platform: state
    entity_id: !input entity_mode
condition: []
action:
  - if:
      - condition: state
        entity_id: input_select.chauffage_mode_bureau
        state: Confort
    then:
      - service: input_number.set_value
        data:
          value: "{{ !input temperature_confort }}"
        target:
          entity_id: input_number.temperature_cible_bureau
  - if:
      - condition: state
        entity_id: input_select.chauffage_mode_bureau
        state: Eco
    then:
      - service: input_number.set_value
        data:
          value: "{{ !input temperature_eco }}"
        target:
          entity_id: input_number.temperature_cible_bureau
mode: single
