blueprint:
  name: Chauffage Mode
  description: Gestion des différents modes de chauffage
  domain: automation

  input:
    entity_mode:
      name: Sélection du mode
      description: Entité de gestion du mode de gestion du chauffage (input_select)
      selector:
        entity:
          domain: input_select
          
    temperature_confort:
      name: Température Confort
      selector:
        number:
          min: 14
          max: 22
          step: 0.5
          mode: slider
          
    temperature_eco:
      name: Température Eco
      selector:
        number:
          min: 14
          max: 22
          step: 0.5
          mode: slider

alias: Chauffage Mode
description: ''
trigger:
  - platform: state
    entity_id: !input entity_mode
condition: []
action:
  - if:
      - condition: state
        entity_id: !input entity_mode
        state: Confort
    then:
      - service: input_number.set_value
        data:
          value: "{{ !input temperature_confort }}"
        target:
          entity_id: input_number.temperature_cible_bureau
  - if:
      - condition: state
        entity_id: !input entity_mode
        state: Eco
    then:
      - service: input_number.set_value
        data:
          value: "{{ !input temperature_eco }}"
        target:
          entity_id: input_number.temperature_cible_bureau
mode: single
